### PR TITLE
Fixes invalid LatLng object error

### PR DESCRIPTION
**Pull request by eelcocramer**
Using the latest leaflet.js (0.7.7) I get an `Invalid LatLng object: (undefined, undefined)` error when calling  `L.RouteBoxer.box`. I hunted this down to [the 'formVertices` function](https://github.com/StephanGeorg/leaflet-routeboxer/blob/master/src/leaflet-routeboxer.js#L126). I don't think the `parseFloat` calls there are necessary. In my case these vars are already floats.

### CODE REVIEW

**Comment by StephanGeorg** [comment]
Sorry, but I cannot reproduce the error. I updated the [example](http://stephangeorg.github.io/leaflet-routeboxer/example/) to the the latest leaflet version.

**Comment by eelcocramer** [comment]
I checked the example and it does not hit that line (I've put a breakpoint on it). Then I checked my code to see the difference and there was an error in my but I'm not quite sure what is happening.

My code was:

```
var route = [
  new L.latLng(50.5, 30.5),
  new L.latLng(50.4, 30.6),
  new L.latLng(50.3, 30.7)
];
```

Notice the `new L.latLng(...)`. This array hits the `formVertices` function and produces an error. When I remove the `new` as they are not needed anyway the `formVertices` function does not get called.

**Comment by eelcocramer** [comment]
Sorry, did not check correctly. I'm still getting the error when I build the array of `L.LatLng`'s myself.

**Comment by eelcocramer** [comment]
I noticed that the script in `dist` makes the call to `formVertices` but the one in `src` does not. Fixing this issue might be as simple as minimising the script in `src` again.

**Comment by StephanGeorg** [comment]
Oh, I see. There was a wrong description in the readme:

Do not pass an array of L.latLng objects to `L.RouteBoxer.box(route, this.distance);` instead you should pass an array of latlng. Something like:

```
var route = [
  [50.5, 30.5],
  [50.4, 30.6],
  [50.3, 30.7]
];
var boxes = L.RouteBoxer.box(route, this.distance);

```

Sorry for confusion...

**Comment by eelcocramer** [comment]
An array of L.latLng's will also work. Thanks for updating the minimised script!

**Pull request closed without merging**
